travis:
  secure:
    BINSTAR_TOKEN: HU/tBsA41m8mh8NKqVUJMQlSvGg8FsJrbZwnY5RBluNa39lu1kuzcympJLBFZkFmXwGSSW6Z9TSZMXcFEPO6J9oQEl8vbsdBv/8T0TFvJOA4cUYo8V9vyIleTG+8eNwi3KE6YKcmkp+ZVraGPSVo/bv/IcHRHy/EPW/aChSCoc/qFs1Ok6kLGCHyWiQwVk5EW9KnB7lGqKTxzRT9tXJXZ0dcWLlbvbIVQxSV2/uWzaYsdANgBi8AsxUZZ0lYjBc7UtjVz0hASnfHE+P86rqgFeEqd174x0HWFN2I9QzwXJ25BNypZoZwvfRpYu1kR0aEHKlugcmysdhbZ7/z5g179+GR8nMv4dMm95sgNGFAYucF081DfOwvVbSy5toBLzUMPXI2Qu3rkXCTYvcYBWulNJPw/gAVjULi0hl1Q8U0ABwXWoPEjEpauTLwoL/G0JVfnPt021j/gbEL83GpWJMYGstxsLQUX1aJiapk0zJ+jS4LBP/tygGoUBCnXl72k0n3iHD8FeuzYAv01JTiYxN6DAlAQckGaAwGlgXINtzw8aOkKlBu3rtJEsr02EJlYWV1iN5ql3V8pA7Asxj2F15k6H379Spt5HnEgmZMjqSB1aBGCBwLHR5cmAkK0KHXUoqkidB08rkQbtGVfvuoa0Tsk4LB4LBFw2YISNnaT05ys+E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
