travis:
  secure:
    BINSTAR_TOKEN: H1G15DIIWvJwmGcrBDUGqcb2NOHylrvS1iSk/MG+Nt2UhiMhOS7OSfxZHqbr+Y82WabsQC2rDKXFDMJGxzx5rCO/2alhjgyVl5YpREplYYsFShF9PISiXHiMoELsRjDCMUepUgWfQXr+OEtcKdbFIEcP/sFsH/6LUR7S+OnGFuudWGtQ9+86gLwkDy+aKh1Pa+RhyRG11E9CJq5dOq1pwpMOshnGkB7E82cEpxryVoZi6wc9IUUmLcb906bwtLuusyM5GdX1x+bbpm1Pu031iShytzeZRJ71i16+mLK5DKJPrPB8aW4d+7N50O3sIFVv5EmVe+DZpUtixVoHzonyiGg8KWD1v6mLFXLlkBUvbLD8YsoXAEH+siPaFv4EHJ/jYns1F4JjLJK/bMYwwdtJrVthWWZKkIgQeFDm+rq8KJdyhbdu/30E1VMgx3Krv0dFHwqvfstYdWDjTtSZxuFNRrKaHWxhNfcqggkwbYcNm5CPCiaRJf4vnBfE4RhJWunPlAp8ix04L6EhjFFZnsJ7lZMkjwWFuiOixKB80lgaHx1AwvafoeI+OXcLQLF6n2T6lXpY84YaeJvKWehRUqRBODLYihbwwQF6xsLOXECCEB2AlK/I5n1gtReJYDpLvQp7Z1wEUZrbexevpHXjCR1FEQ+IG/Cq0P8/L+BFjSbsoiI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
